VERSION="v0.0.16"
CONST_LISTEN_PORT=2055
CONST_LISTEN_ADDRESS="0.0.0.0"
CONST_LOCAL_HOSTS=["192.168.48.0/22"]
CONST_PROCESSING_INTERVAL=60
MAXMIND_LICENSE_KEY="YOUR_MAXMIND_LICENSE_KEY"
MAXMIND_URL = f"https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City-CSV&license_key={MAXMIND_LICENSE_KEY}&suffix=tar.gz"
CONST_ROUTER_IPADDRESS=["192.168.49.1"]
IS_CONTAINER=1